server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # Opcional: Proxy para evitar problemas de CORS en desarrollo
    location /api/ {
   # asi funciona para doker
   # proxy_pass http://app_newfarma:8000; # Nombre del servicio en docker-compose
    proxy_pass pure-charisma.railway.internal; # URL del backend en Railway
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
}
}

