server {
    listen 80;
    server_name _;
    
    # Resolver obligatorio para Railway
    resolver 8.8.8.8 valid=10s;
    
    # Variable para forzar resolución DNS en cada request
    set $backend "http://pure-charisma.railway.internal";

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
        
        # Headers para cache
        expires -1;
        add_header Cache-Control "no-store, no-cache, must-revalidate";
    }

    location /api/ {
    proxy_pass https://pure-charisma-production-5f5b.up.railway.app;
    proxy_set_header Host pure-charisma-production-5f5b.up.railway.app;
    
    # Mismos headers que arriba
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
}
}